version: "3.7"

x-api-base: &base-api
  image: node:12.14.1
  working_dir: /usr/app
  volumes:
    - .:/usr/app

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: todos
      POSTGRES_USER: todos
      POSTGRES_DB: todos
  api:
    << : *base-api
    command: npm run dev
    depends_on:
      - postgres
    environment:
      PORT: 8000
      DATABASE_URL: postgres://todos:todos@postgres:5432/todos
    ports:
      - 8000:8000
  install:
    << : *base-api
    command: npm install
